### PR TITLE
Support Accelerators and integrate GPU VMI

### PR DESCRIPTION
**Pull request by js-ts**
Default is still set to no GPU compute nodes

To use GPUs

Open this file
ops/tf/vars.tfvars

Change 
accelerator_count = 0 -> 1

# Comment this line
gcp_boot_image_compute = "projects/forrest-dev-407420/global/images/bacalhau-ubuntu-2004-lts-test"
# And Uncomment this one to use GPUs
# gcp_boot_image_compute = "projects/forrest-dev-407420/global/images/bacalhau-common-cu121-v20230925-ubuntu-2004-lts-test-16"

Fixes: https://github.com/bacalhau-project/expanso-planning/issues/382

### CODE REVIEW

**Review by frrist — CHANGES_REQUESTED** [review]
Please rebase this onto the parent branch. There are too many unrelated changes in here. I expect the changes here to be small, should just be adding a new image type and a few vars to deploy with it.

Do you think it makes sense to add a new module for compute nodes with accelerators since they will use different images?

**Comment by wdbaruni** [comment]
@frrist @js-ts what is the status of this PR?

**Comment by js-ts** [comment]
David said that supporting GPUs is not p0 for the current MKPT release. so didn't merge it.

**Comment by frrist** [comment]
Closing for now, we can refocus this work into building a VMI in https://github.com/bacalhau-project/bacalhau-vmi that supports GPUs

**Pull request closed without merging**
