### PR TITLE
Update README.md: installation options

### PR DESCRIPTION
**Pull request by Nasfame**
- [x] Add bacalhau client installation option with Go1.18
- [x] Relates to #3029

### CODE REVIEW

**Comment by lukemarsden** [comment]
Why? I'd rather just use bacalhau's officially supported installation mechanism. Also, we need to pin to bacalhau 1.0.3 until their GPU issue is fixed

**Comment by Nasfame** [comment]
@lukemarsden Recently experienced the official installation method failing: #3030

**Comment by simonwo** [comment]
Not the right place for this, open a PR against this page instead please: https://docs.bacalhau.org/getting-started/installation

**Comment by Nasfame** [comment]
@simonwo can u add me to gitbook teams/members? 

TLDR: https://docs.gitbook.com/account-management/plans/apply-for-the-non-profit-open-source-plan

**Comment by rossjones** [comment]
@Nasfame we don't use gitbook. You can just pull that repo and make a change like any other repo.

**Comment by Nasfame** [comment]
@rossjones can u help me in finding the markdown source code to: https://docs.bacalhau.org/getting-started/installation/

**Comment by Nasfame** [comment]
Nevermind got it: https://github.com/bacalhau-project/docs.bacalhau.org

**Comment by Nasfame** [comment]
@rossjones can u grant me contributor access to the repo?

**Comment by rossjones** [comment]
> @rossjones can u grant me contributor access to the repo?

Unfortunately not as I don't have the access to do that.

**Comment by Nasfame** [comment]
@simonwo i think its more fitting to specify the go installation method over here as well!!

**Comment by simonwo** [comment]
This is meant to be a quick start, not exhaustive documentation. The quickest start is definitely the install.sh script.

**Pull request closed without merging**
