### PR TITLE
3420 storyboard for nodestable

### PR DESCRIPTION
**Pull request by aronchick**
Allowing rendering of jobs table via storybook

Lots of package.json clean up in order to make this work.

### CODE REVIEW

**Review by frrist — APPROVED** [review]
assuming this is only modifying the webui package lgtm

**Comment by wdbaruni** [comment]
@aronchick is this still useful?

**Comment by aronchick** [comment]
Will need complete rework I'm sure - put it into draft?

**Comment by wdbaruni** [comment]
Closing this as webui has been reimplemented using new framework

**Pull request closed without merging**
