### PR TITLE
whitelist: python package manager

### PR DESCRIPTION
**Pull request by Nasfame**
whitelist: conda, python

### CODE REVIEW

**Comment by Nasfame** [comment]
@iand it would be great if u could review it

**Review by frrist — APPROVED** [review]
Looks good to me. Will wait for Simon make the final call.

**Comment by frrist** [comment]
@Nasfame curious to know what motivates this change.

**Comment by Nasfame** [comment]
@frrist Asked out in the bacalhau workspace in slack over issue of installing custom  python dependencies for Decenter-AI: https://decenter-ai.streamlit.app

@simonwo encouraged me to raise a pr for whitelisting python deps

Here is the thread: https://bacalhauproject.slack.com/archives/C055K39J9QW/p1695922870924579

**Comment by Nasfame** [comment]
Thanks @rossjones . We can now finally enable some disabled features of http://decenter-ai.streamlit.app

**Pull request merged**
