### PR TITLE
Moving spelling file to its own directory (for vscode integration) and skipping draft PRs

### PR DESCRIPTION
**Pull request by aronchick**
…d skipping draft PRs on CI

### CODE REVIEW

**Review by simonwo — CHANGES_REQUESTED** [review]
I've not seen any discussion about skipping draft PRs. What's the thinking behind that? I would prefer they run in CI.

**Comment by aronchick** [comment]
> I've not seen any discussion about skipping draft PRs. What's the thinking behind that? I would prefer they run in CI.

Our build pipeline often takes 10 minutes+ to run. If a PR is in draft, why would we want it to run? The developer of the PR is saying it's not ready for review.

**Comment by wdbaruni** [comment]
> > I've not seen any discussion about skipping draft PRs. What's the thinking behind that? I would prefer they run in CI.
> 
> Our build pipeline often takes 10 minutes+ to run. If a PR is in draft, why would we want it to run? The developer of the PR is saying it's not ready for review.

Generally the developer should wait for the CI checks to pass before publishing the PR and marking it ready for review

**Comment by aronchick** [comment]
I guess my issue is that if draft PRs are slowing actual ready to ship PRs, that seems not ideal.

**Review by frrist — APPROVED** [review]
lgtm. Might add a note in the CONTRIBUTING.md stating PR's labeled wit 'do-not-merge' or 'wip' will not trigger CI.

**Review by aronchick — COMMENTED** [review]
done

**Pull request merged**
