### PR TITLE
adding testing bacalhau running script

### PR DESCRIPTION
**Pull request by aronchick**

### CODE REVIEW

**Review by simonwo — COMMENTED** [review]
This PR looks identical to #3154 ??

**Comment by aronchick** [comment]
> This PR looks identical to #3154 ??

The issue is that we are slow at approving PRs, i started using stacked branches so each PR was small, but worked when done in order - https://andrewlock.net/working-with-stacked-branches-in-git-is-easier-with-update-refs/ - this minimizes pain, but requires we do things in order (which is not clear to me how to signal). This one IS different, but only very small so it looks the same.

**Review by simonwo — COMMENTED** [review]
Needs an update to remove stuff already committed/reviewed.

**Review by simonwo — APPROVED** [review]

**Comment by aronchick** [comment]
https://github.com/bacalhau-project/bacalhau/issues/3219

**Pull request merged**
