### PR TITLE
Pull bug fixes and update of job version

### PR DESCRIPTION
**Pull request by MichaelHoepler**
This PR mainly contains bug fixes, slight adjustments to the overall structure

### CODE REVIEW

**Review by rossjones — CHANGES_REQUESTED** [review]
This PR reverts work that has been done over the several weeks, and will result in lost features/functionality.  I think we should probably close this and look again at what actually needs to be merged. x

**Comment by MichaelHoepler** [comment]
Can you please specify what features/functionality will be lost? There will be nothing overwritten from the main branch.

**Comment by MichaelHoepler** [comment]
@wdbaruni @rossjones

**Comment by rossjones** [comment]
It re-adds apps/job-info-consumer which was deleted.
It deletes the Earthfile for clients.
It deletes the config show and default commands
etc.

Even if it didn't delete, or re-introduce things, or change behaviour, it's 174 commits and >1000 files and is unreviewable.

**Comment by frrist** [comment]
@MichaelHoepler what was the goal of this PR? Are you looking to make changes _only_ to documentation?

**Comment by MichaelHoepler** [comment]
@rossjones Thanks, understood. 
@frrist Yes this was just meant to make changes to the docs. I have created a new branch from main and will only move the changes of the documentation pages over.

**Pull request closed without merging**
