### PR TITLE
Fix builds for OSX 

### PR DESCRIPTION
**Pull request by rossjones**
CircleCI are [deprecating their x86 OSX machines](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718), on the basis that we can then build on arm64 - although there doesn't seem to be a good answer to "how do we test on osx x86?".

Some deprecations are happening in 2 weeks, which this PR hopes to avoid, and will then allow us to continue until the end of Jan 24 at which point x86 will no longer be available.

At the same time this PR switches to building `darwin-arm64` on an M1 machine. Best review by commit as the first contains an auto-format that touches lots of parts other than the actual change at the top.

```
  darwin-amd64:
    # Note - not an actual ARM macOS machine (https://circleci.canny.io/cloud-feature-requests/p/support-new-m1-arm-based-macs)
    macos:
      xcode: 15.1
    resource_class: macos.x86.medium.gen2
```

### CODE REVIEW

**Review by simonwo — APPROVED** [review]
LGTM.

**Comment by rossjones** [comment]
Annoyingly the test that is often flaky on windows, is flaky now we actually test on darwin-arm64, but doesn't show up locally.

**Comment by frrist** [comment]
This test (Retries) fails for me more than it passes. Would it be worth skipping it (`t.Skip`)  for these specific envs, and creating an issue to fix it?

**Comment by simonwo** [comment]
> This test (Retries) fails for me more than it passes. Would it be worth skipping it (t.Skip) for these specific envs, and creating an issue to fix it?

We should only `Skip` tests where it's not possible to support the test or the functionality itself in the environment. That's not the case here, the test just sucks.

Create an issue if needed, but I'd be happier if we just fixed it!

**Comment by frrist** [comment]
Here is my reasoning for skipping it in this specific case:
- `TestRetriesSuite` runs in the linux environment, generally without flake. We have coverage of the scenario being tested.
- On this branch the test has run
  - 5 times with a 0% success rate for the darwin env
  - 7 times with an 87% success rate for the windows env
([source](https://app.circleci.com/insights/github/bacalhau-project/bacalhau/workflows/test_darwin_arm64/tests?branch=upgrade-osx-machine-circle-deprecation))

Given the test is passing in the Linux environment I believe we can gain some confidence the behavior is being exercised and works as expected. By opting to skip the test in the flaky environments (darwin arm and windows amd) we can increase developer velocity and save some circle CI credits. 

My hunch regarding the failure is related to non-determinism in the timing of it: `TestRetriesSuite/TestRetry/publish-partial-failure` is almost always the culprit. It uses ["good-guy-1"](https://github.com/bacalhau-project/bacalhau/blob/main/pkg/test/requester/retries_test.go#L238) that's [programmed to sleep](https://github.com/bacalhau-project/bacalhau/blob/main/pkg/test/requester/retries_test.go#L112) for [some time](https://github.com/bacalhau-project/bacalhau/blob/main/pkg/test/requester/retries_test.go#L37C5-L37C22). The proper fix will likely entail adding a mockable clock in the call path of the test. I've filed an issue for it here: https://github.com/bacalhau-project/bacalhau/issues/2841

**Review by frrist — APPROVED** [review]
I am hesitant to merge a change that increases test flakiness. Aside from that change LGTM.

**Comment by rossjones** [comment]
> My hunch regarding the failure is related to non-determinism in the timing of it: TestRetriesSuite/TestRetry/publish-partial-failure is almost always the culprit. It uses "good-guy-1" that's programmed to sleep for some time

Yeah, I thought it might be the execution state update being delayed and appearing after the job state becomes terminal (and we do the assertions) and I guess that sleep might cause that.  

Given it appears on arm64 (M1) as well now, although I can't replicate on my M2, we should probably take the pain in fixing the time issues although if we just want the bad actor to finish first, maybe we should just wait for it to finish?

**Comment by frrist** [comment]
I was able to get a failure locally on my M1:
```
=== RUN   TestRetriesSuite/TestRetry
    --- FAIL: TestRetriesSuite/TestRetry (0.75s)
=== RUN   TestRetriesSuite/TestRetry/publish-partial-failure
07:58:22.362 | INF pkg/executor/noop/executor.go:96 > starting execution
07:58:22.403 | INF pkg/executor/noop/executor.go:96 > starting execution
07:58:22.419 | INF pkg/compute/executor.go:183 > cleaning up execution [NodeID:QmVwZ5EY] [execution:e-308d3753-4be6-4869-9e90-93637c1fcf94] [job:22a449d9-0165-4341-8b3c-cfd24f62e705]
07:58:22.419 | ERR pkg/compute/executor.go:452 > Publishing execution e-308d3753-4be6-4869-9e90-93637c1fcf94 failed error="failed to publish result: I am a bad publisher" [NodeID:QmVwZ5EY] [execution:e-308d3753-4be6-4869-9e90-93637c1fcf94] [job:22a449d9-0165-4341-8b3c-cfd24f62e705]
07:58:22.601 | INF pkg/executor/noop/executor.go:96 > starting execution
07:58:22.612 | INF pkg/compute/executor.go:183 > cleaning up execution [NodeID:QmVwZ5EY] [execution:e-1025c3d4-1dea-4d56-97a2-7969c0685d19] [job:22a449d9-0165-4341-8b3c-cfd24f62e705]
07:58:22.613 | ERR pkg/compute/executor.go:452 > Publishing execution e-1025c3d4-1dea-4d56-97a2-7969c0685d19 failed error="failed to publish result: I am a bad publisher" [NodeID:QmVwZ5EY] [execution:e-1025c3d4-1dea-4d56-97a2-7969c0685d19] [job:22a449d9-0165-4341-8b3c-cfd24f62e705]
07:58:22.666 | INF pkg/compute/executor.go:183 > cleaning up execution [NodeID:QmSmEztt] [execution:e-7df55c89-3b5f-4d69-89d7-ade141424738] [job:22a449d9-0165-4341-8b3c-cfd24f62e705]
07:58:22.681 | ERR pkg/orchestrator/worker.go:157 > Failed to process evaluation 34c1c79e-2332-42c4-8243-0e5edb0e818f error="failed to process plan with planner *planner.StateUpdater: execution e-7df55c89-3b5f-4d69-89d7-ade141424738 has version 6 but expected 5"
07:58:22.799 | ERR pkg/orchestrator/planner/logging_planner.go:23 > Job 22a449d9-0165-4341-8b3c-cfd24f62e705 failed due to `failed to publish result: I am a bad publisher`
    retries_test.go:317: 
        	Error Trace:	/Users/frrist/Workspace/src/github.com/bacalhau-project/bacalhau/pkg/test/requester/retries_test.go:317
        	            				/Users/frrist/Workspace/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestRetriesSuite/TestRetry/publish-partial-failure
        	Messages:   	Expected 1 executions in state Cancelled, found 0
```
And on the next run a sucess:
```
--- PASS: TestRetriesSuite (12.18s)
=== RUN   TestRetriesSuite/TestRetry
    --- PASS: TestRetriesSuite/TestRetry (0.53s)
=== RUN   TestRetriesSuite/TestRetry/publish-partial-failure
07:59:25.479 | INF pkg/executor/noop/executor.go:96 > starting execution
07:59:25.501 | INF pkg/compute/executor.go:183 > cleaning up execution [NodeID:QmZfh5aZ] [execution:e-120b91b3-237d-43ea-a46f-cb79f5a645c9] [job:84e3df33-0f61-4cfa-9bd7-e86f88ee9687]
07:59:25.501 | ERR pkg/compute/executor.go:452 > Publishing execution e-120b91b3-237d-43ea-a46f-cb79f5a645c9 failed error="failed to publish result: I am a bad publisher" [NodeID:QmZfh5aZ] [execution:e-120b91b3-237d-43ea-a46f-cb79f5a645c9] [job:84e3df33-0f61-4cfa-9bd7-e86f88ee9687]
07:59:25.521 | INF pkg/executor/noop/executor.go:96 > starting execution
07:59:25.642 | INF pkg/executor/noop/executor.go:96 > starting execution
07:59:25.653 | INF pkg/compute/executor.go:183 > cleaning up execution [NodeID:QmZfh5aZ] [execution:e-c52977ee-a289-4841-98ae-f5d5a379b4e6] [job:84e3df33-0f61-4cfa-9bd7-e86f88ee9687]
07:59:25.653 | ERR pkg/compute/executor.go:452 > Publishing execution e-c52977ee-a289-4841-98ae-f5d5a379b4e6 failed error="failed to publish result: I am a bad publisher" [NodeID:QmZfh5aZ] [execution:e-c52977ee-a289-4841-98ae-f5d5a379b4e6] [job:84e3df33-0f61-4cfa-9bd7-e86f88ee9687]
07:59:25.71 | INF pkg/executor/noop/executor.go:157 > cancel execution
07:59:25.736 | ERR pkg/orchestrator/planner/logging_planner.go:23 > Job 84e3df33-0f61-4cfa-9bd7-e86f88ee9687 failed due to `failed to publish result: I am a bad publisher`
07:59:25.771 | INF pkg/compute/executor.go:183 > cleaning up execution [NodeID:QmRhPH9M] [execution:e-bd4bfaf1-2474-4ebd-a66d-0f6713df0d58] [job:84e3df33-0f61-4cfa-9bd7-e86f88ee9687]
07:59:25.772 | ERR pkg/compute/executor.go:452 > Publishing execution e-bd4bfaf1-2474-4ebd-a66d-0f6713df0d58 failed error="execution e-bd4bfaf1-2474-4ebd-a66d-0f6713df0d58 is in state Cancelled but expected one of [Running]" [NodeID:QmRhPH9M] [execution:e-bd4bfaf1-2474-4ebd-a66d-0f6713df0d58] [job:84e3df33-0f61-4cfa-9bd7-e86f88ee9687]
07:59:25.772 | ERR pkg/compute/executor.go:460 > Failed to update execution (e-bd4bfaf1-2474-4ebd-a66d-0f6713df0d58) state to failed: execution e-bd4bfaf1-2474-4ebd-a66d-0f6713df0d58 is in terminal state Cancelled and cannot transition to Failed error="execution e-bd4bfaf1-2474-4ebd-a66d-0f6713df0d58 is in terminal state Cancelled and cannot transition to Failed" [NodeID:QmRhPH9M] [execution:e-bd4bfaf1-2474-4ebd-a66d-0f6713df0d58] [job:84e3df33-0f61-4cfa-9bd7-e86f88ee9687]
```

One the key differences in the Fail/Pass it the line below in the success case:
> 07:59:25.71 | INF pkg/executor/noop/executor.go:157 > cancel execution
> 2332-42c4-8243-0e5edb0e818f error="failed to process plan with planner *planner.StateUpdater: execution e-7df55c89-3b5f-4d69-89d7-ade141424738 has version 6 but expected 5"

Perhaps there is a race in cancellation due to the [executor_buffer calling cancel in a go routine](https://github.com/bacalhau-project/bacalhau/blob/e147d2d6c03c31d5bc471d365340f040604538d6/pkg/compute/executor_buffer.go#L216)? The execution could already be in a failed state when cancel is evaluated, and thus cannot be transition from `Failed` to `Canceled`?

**Pull request merged**
