### PR TITLE
backward compatibility for env variables

### LINKED ISSUE #4555: backward compatibility broken for env variables
With v1.5.0, we've kept support for configuring bacalhau with environment variables only to keep backward compatibility support with v1.4.0. However, the env variable have been renamed for most of the configurations and we are no longer maintaining backward compatibility

For example, `BACALHAU_NODE_NETWORK_ORCHESTRATORS` has been renamed to `BACALHAU_COMPUTE_ORCHESTRATORS`, and `BACALHAU_NODE_NETWORK_ADVERTISEDADDRESS` is now `BACALHAU_ORCHESTRATOR_ADVERTISE`

### PR DESCRIPTION
**Pull request by udsamani**
closes #4555

### CODE REVIEW

**Comment by udsamani** [comment]
Screenshot 2024-09-30 at 13 15 24

**Comment by wdbaruni** [comment]
looks good. Though we need to add the env vars to all the cli flags

**Review by wdbaruni — CHANGES_REQUESTED** [review]
looks good. Though we need to add the env vars to all the cli flags

**Comment by wdbaruni** [comment]
@frrist please review

**Review by wdbaruni — APPROVED** [review]

**Pull request merged**
